# Generated by Django 4.2.14 on 2024-07-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_commment_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commment',
            new_name='Comment',
        ),
    ]
